---
title: "glm balanced link cloglog"
output:
  pdf_document: default
  html_document: default
date: "2025-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
load("~/GitHub/Mineria/DATA/dataaaaaaaaaaaaaa.RData")
datatrain <- data_reducida_plus[1:7000, !(names(data_reducida_plus) %in% "group")]
datatest<-data_reducida_plus[7001:10000,!(names(data_reducida_plus) %in% "group")]
datatrain$Exited <- factor(datatrain$Exited, levels=c(0,1), labels=c("neg","pos"))
datatrain$NumOfProducts_grupo <- as.character(datatrain$NumOfProducts_grupo) 
datatrain$NumOfProducts_grupo[datatrain$NumOfProducts_grupo == "3 o más"] <- "3_plus" 
datatrain$NumOfProducts_grupo <- factor(datatrain$NumOfProducts_grupo)
```
```{r}
library(caret)
library(ROSE)
library(pROC)

set.seed(123)

rose_ratios <- seq(0.25, 0.50, by = 0.05)

compute_kpis <- function(obs, pred_class, prob_pos) {
  
  cm <- confusionMatrix(pred_class, obs, positive = "pos")
  
  auc <- roc(obs, prob_pos)$auc
  
  data.frame(
    Sensitivity = cm$byClass["Sensitivity"],
    Specificity = cm$byClass["Specificity"],
    PPV         = cm$byClass["Pos Pred Value"],
    NPV         = cm$byClass["Neg Pred Value"],
    Accuracy    = cm$overall["Accuracy"],
    F1          = cm$byClass["F1"],
    AUC         = auc
  )
}

results_all <- data.frame()
cutpoints <- seq(0.1, 0.5, by = 0.05)

for (p in rose_ratios) {
  
  train_ctrl <- trainControl(
    method = "cv",
    number = 10,
    sampling = function(x, y) {
      data_temp <- data.frame(x, Exited = y)
      data_rose <- ROSE(Exited ~ ., data = data_temp, p = p, seed = 1)$data
      list(
        x = data_rose[, -which(names(data_rose)=="Exited")],
        y = data_rose$Exited
      )
    },
    classProbs = TRUE,
    summaryFunction = twoClassSummary,
    savePredictions = "final"
  )
  
  # Modelo GLM con enlace cloglog
  fit <- train(
    Exited ~ .,
    data = datatrain,
    method = "glm",
    family = binomial(link = "cloglog"),
    trControl = train_ctrl,
    metric = "ROC"
  )
  
  # OUT-OF-FOLD (train)
  prob_train <- fit$pred$pos
  obs_train  <- fit$pred$obs
  
  # Test interno (predict sur datatrain)
  prob_test  <- predict(fit, datatrain, type="prob")[, "pos"]
  obs_test   <- datatrain$Exited
  
  for (cut in cutpoints) {
    
    # TRAIN KPIs
    pred_train_cut <- factor(ifelse(prob_train > cut, "pos", "neg"),
                             levels = c("neg","pos"))
    kpi_train <- compute_kpis(obs_train, pred_train_cut, prob_train)
    
    # TEST KPIs
    pred_test_cut <- factor(ifelse(prob_test > cut, "pos", "neg"),
                            levels = c("neg","pos"))
    kpi_test <- compute_kpis(obs_test, pred_test_cut, prob_test)
    
    # Store results
    results_all <- rbind(results_all, data.frame(
      ROSE_p    = p,
      Cutoff    = cut,
      F1_Train   = kpi_train$F1,
      F1_Test    = kpi_test$F1,
      Sens_Train = kpi_train$Sensitivity,
      Sens_Test  = kpi_test$Sensitivity,
      Spec_Train = kpi_train$Specificity,
      Spec_Test  = kpi_test$Specificity,
      PPV_Train  = kpi_train$PPV,
      PPV_Test   = kpi_test$PPV,
      NPV_Train  = kpi_train$NPV,
      NPV_Test   = kpi_test$NPV,
      ACC_Train  = kpi_train$Accuracy,
      ACC_Test   = kpi_test$Accuracy,
      AUC_Train  = kpi_train$AUC,
      AUC_Test   = kpi_test$AUC
    ))
  }
}

```
```{r}
results_all
```


